### PR TITLE
Support input from all controller channels.

### PR DESCRIPTION
**Pull request by yo1dog**
Adds listening to input from all controller channels instead of just 0. This restores functionality for those w/o a functioning P1 controller port.

Many lines touched but functionally a small change. The meat is the [additions to `util.c`](https://github.com/emukidid/swiss-gc/pull/694/files#diff-e35d5137326c7d4e6e9f2340f6da99efaa198739394d5a522717702a41b6c3f8). The rest is simply replacing `PAD_ButtonsHeld(0)`, `PAD_StickX(0)`, `PAD_StickY(0)` with `padsButtonsHeld()`, `padsStickX()`, `padsStickY()`. Will be important to use these functions going forward to maintain support for all controllers.

Implementation is straightforward for buttons: bitwise-or the button states of all controllers. For analog inputs, use the value with the largest magnitude. That is, for a given axis, whichever pad has the greatest absolute value, use the value for that pad.

For example, if we are reading the StickY axis and P1 is slightly off center upwards at 4 and P2 is held downwards at -98, -98 would be used. If P1 was pressing downward halfway at -52 and P2 was pressing upwards fully at 99, 99 would be used.

I replaced the only instance of `PAD_ButtonsDown` with `padsButtonsHeld` as the relevant comment made it sound appropriate: "L Trigger held down ignores the fact that there's a component cable plugged in."

Tested on my personal DOL-101. Works great.

### CODE REVIEW

**Comment by yo1dog** [comment]
I'm not the most familiar with GitHub. How is it possible that you pushed to my fork/repo?

**Comment by Extrems** [comment]
Ah, there's a checkbox on the right side labeled "Allow edits by maintainers".

I just rebased it and resolved the conflicting changes. I still need to review it properly.

**Comment by yo1dog** [comment]
Ahhh that it explains it. I figured it was something like that but I was looking in the repo settings. I was very confused for a bit there.Thanks

**Comment by FishamanP** [comment]
This would be a very useful addition to Swiss! Could it possibly be reviewed and merged soon?

**Pull request merged**
