### PR TITLE
Updated list view and region icons

### PR DESCRIPTION
**Pull request by cristofercruz**
I've made a few more adjustments for your consideration. The Standard list view looks a bit messy with variable text scale and region icons were a little muddled.

- Added option to generate ellipsis clipped texts in horizontal orientation
- Cleaned up Standard list view by changing name display to use fixed scale and clip with ellipsis
- Use calculated text scale in Standard list for the selected row to show full unclipped name
- Replaced country flag images for region icons with cleaner versions
- Revert to use displayName instead of fullGameName for name display in lists
- Various adjustments to text and image placements

Appreciate any feedback.

list-clipped
list-selected
list-open

### CODE REVIEW

**Comment by emukidid** [comment]
Without having tried this yet, the vertical alignment on the standard file browser text bugs me, can you centre it (based on size) please.

**Comment by cristofercruz** [comment]
@emukidid not sure what you had in mind since on standard list the title would run into the size label if completely centered on the row. I made further adjustments to center titles within the available space instead. Check out the proposed changes when you get some time.

**Comment by emukidid** [comment]
I checked it out, here's what I mean about vertical alignment (excuse the JPEG artifacting):
image

**Comment by cristofercruz** [comment]
@emukidid I've centered the title text vertical within each row. Also meant max text scale needed to be set lower to avoid title running into size label when title is long and size is in MB.

Can you checkout these changes? Let me know what you think.

**Comment by Extrems** [comment]
I've been driving myself to insanity finding where the country flags came from, and then I remembered this pull request. :sweat_smile:

We're needing a few more:
- Australia
- France
- Germany
- Italy
- Netherlands
- South Korea
- Spain
- Sweden
- World, somehow

**Comment by cristofercruz** [comment]
@Extrems do you need these at the same 30x20 resolution or are these for some other use case?

**Comment by Extrems** [comment]
Same resolution, but it would be good to also have them in 45x30 for future 720p support.

**Pull request merged**
