### PR TITLE
New set of device images

### PR DESCRIPTION
**Pull request by cristofercruz**
### I have created a set of device images that look better against the dark Swiss ui.

- Adjusted the sizing of the device image in list view to take advantage of the available width
- Vertically centered the images in the device selection window.

Some screenshots embedded below for review and consideration:

### CODE REVIEW

**Comment by Extrems** [comment]
"SX"? Is this some random trademark dodging amongst everything else?

Great work as always.

**Comment by Extrems** [comment]
I'm not sure where the "DOL-C" or "DOL-CC" markings come from. It's supposed to be "RTC-DOL".

**Comment by cristofercruz** [comment]
It was just filler because of the tight space. I stacked the text instead; should be good now.

**Comment by Diegorella** [comment]
man, you read my thoughts!

**Pull request merged**
