### PR TITLE
Mkisofs fixes

### PR DESCRIPTION
**Pull request by rapperskull**
`mkisofs` has been replaced with `xorriso -as mkisofs` on both Windows and Linux.
I also created a "cube" target to build everything except _geckoserver_ (the Linux version can not be built under Windows) and the full package.

### CODE REVIEW

**Comment by Extrems** [comment]
It'd be much preferable to use `xorriso -as mkisofs` or `xorrisofs` on Windows instead, or switch to native `xorriso` entirely.

**Comment by Extrems** [comment]
`xorriso -as mkisofs` is not native `xorriso`. I also question the `cube` target.

**Comment by rapperskull** [comment]
The cube target is just a shorthand to avoid building PC stuff (not always needed). As for native xorriso, I think there's not a 1:1 correspondence between flags. Just as an example, reading the help file, I was not able to find something like `-no-emul-boot`.

**Comment by rapperskull** [comment]
I saw you changed the Makefile to use xorriso on Windows, but the mkisofs syntax is not compatible. You should use `xorriso -as mkisofs`, otherwise it will not recognize the parameters.

**Comment by Extrems** [comment]
`xorriofs` is a shortcut for `xorriso -as mkisofs`.

**Comment by rapperskull** [comment]
Sorry, completely missed the "fs" part at the end. Then I think this pull request can be closed. I'll leave the cube target as a suggestion, if you want to implement it.

**Pull request closed without merging**
