### PR TITLE
Add Github Workflow and update README.md

### PR DESCRIPTION
**Pull request by bladeoner**
@Extrems thank you for your patience.

The Github Workflow will as mentioned only build the Linux Gecko server not the Windows one.

Please test compiling first on your own environment before adding the PR, because I had to adjust the makefile and I don't have another environment to test.

### CODE REVIEW

**Comment by bladeoner** [comment]
@Extrems I can't get the "make: i686-w64-mingw32-gcc: Command not found" error fixed on both Ubuntu or Windows.

You can add the PR or close it.

**Comment by Extrems** [comment]
I know how to fix all this. I'll fix it later.

**Comment by bladeoner** [comment]
Thanks, appreciated!

**Comment by bladeoner** [comment]
I am one step further on my own machine it compiles swissserver.exe, in the build I am getting an error which I'm looking into.
[logfile.txt](https://github.com/emukidid/swiss-gc/files/8108262/logfile.txt)

I've install the following packages to get it compiled:
binutils-mingw-w64-i686
g++-mingw-w64-i686

**Comment by bladeoner** [comment]
@Extrems I got it working, the swissserver.exe file is also included.

Hereby recap of what I did:
- I had to add the following packages to the Github Workflow to be able to compile swissserver.exe:
binutils-mingw-w64-i686
g++-mingw-w64-i686
- The Linux swissserver didn't build after that because it needs the mingw-w64 package which is conflicting with the g++-mingw-w64-i686 package.
- The g++-mingw-w64-i686 package is version 8.3.0 which is an older version. The Devkitpro docker image is pointing to another repository then a normal Ubuntu 20.04 machine, in that repository the highest version version 8.3.0 is. Adjusting the repository is a difficult task and can break other things, I tried that workin on another project.
- I had to separate the swissserver Windows build from the Linux build.
- I added a new value in the make file called 'github'  which skips the clean step to prevent the swissserver.exe from being removed.

I got a succesful build on the following page where you can see and download the Artifacts containing the files:
https://github.com/bladeoner/swiss-gc/actions/runs/1877222449

**Comment by Extrems** [comment]
Please use xorrisofs instead of genisoimage. There's still lots of unnecessary and wrong stuff in there.

**Comment by bladeoner** [comment]
It is now using xorrisofs and I optimized the makefile.

**Comment by bladeoner** [comment]
@Extrems is the PR fine like it is now or do you want to change some parts?

**Comment by Extrems** [comment]
Yes, I still need to look at this properly when I have time.

**Pull request merged**
